title: Kraken Stress Testing Toolkit
description: Документация

url: "https://kdocs.g-soft.info/"

plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc
relative_links:
  enabled: true
  collections: true

theme: jekyll-theme-architect

#########
markdown: kramdown


collections:
  episodes:
    output: true
  seasons:
    output: true
  characters:
    output: true


defaults:
  - scope:
      path: ""
      type: "episodes"
    values:
      layout: "episode"
  - scope:
      path: ""
      type: "characters"
    values:
      layout: "character"
  - scope:
      path: ""
      type: "seasons"
    values:
      layout: "season"


########

sass:
  sass_dir: _sass
  style: compressed

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_id: toc
  list_class: section-nav
  sublist_class: ''
  item_class: toc-entry
  item_prefix: toc-
  permalink: true

include: 
  - nav.md

exclude: ["README.md"]