title: Kraken Stress Testing Toolkit
description: Документация

url: "https://kdocs.g-soft.info/"
locale: ru_RU

plugins:
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

relative_links:
  enabled: true
  collections: true

#theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
#########
relative_links:
  enabled: true
  collections: true
include:
  - README.md
########

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" 



permalink:   /:categories/:title/


exclude: ["README.md"]