plugins:
  - jekyll-relative-links
  - search
  - jekyll-sitemap
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md

theme: jekyll-theme-architect
title: [The title of your site]
description: [A short description of your site's purpose]